config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  get 'authenticate/login'
  post 'authenticate/login'

  get 'authenticate/logout'

  
  resources :grades
  resources :parents
  resources :students
  resources :teachers

end

app/models/grade.rb
class Grade < ActiveRecord::Base
  belongs_to :student 
end

app/models/parent.rb
class Parent < ActiveRecord::Base
  belongs_to :student 
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :teacher
  has_many :parents
  has_many :grades 
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_many :students 
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_filters.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_filter :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/grades_controller.rb
module Admin
  class GradesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Grade.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Grade.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/parents_controller.rb
module Admin
  class ParentsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Parent.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Parent.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/students_controller.rb
module Admin
  class StudentsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Student.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Student.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/teachers_controller.rb
module Admin
  class TeachersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Teacher.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Teacher.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def login
      if request.post?
        user = User.find_by(email: params[:email])

        if user && user.authenticate(params[:password])
          session[:user_id] = user.id
          redirect_to dishes_path, notice: "Login successful."
        else
          flash[:notice] = "Incorrect password. Please try again."
        end
      end
    end

    def logout
      session[:user_id] = nil
      redirect_to authenticate_login_path, notice: "See you real soon!"
    end
end

app/controllers/grade_controller.rb
class GradeController < ApplicationController
  def show
  end

  def new
    @grade = Grade.new
  end

  def create
  end

  def destroy
  end
end

app/controllers/parent_controller.rb
class ParentController < ApplicationController
  def index
    @parents = Parent.all
  end

  def new
    @parent = Parent.new
  end

  def create
  end

  def destroy
  end
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
  def index
    @students = Student.all
  end

  def show
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'student was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :email, :password_digest)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/grade_helper.rb
module GradeHelper
end

app/helpers/parent_helper.rb
module ParentHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/dashboard/index.html.erb
<h1>Welcome to the Shermer High School Gradebook</hi>
<h3>Please log in</h3>
<%= form_tag do %>
  <p><%= email_field_tag :email, nil, placeholder: "Email" %></p>
  <p><%= password_field_tag :password, nil, placeholder: "Password" %></p>
  <%= submit_tag %>
<% end %>
<br>
<br>

<%= link_to 'Add New Grade', new_grade_path %>
<%= link_to 'Create New Parent', new_parent_path %>
<%= link_to 'Create New Student', new_student_path %>
<%= link_to 'Create New Teacher', new_teacher_path %>

app/views/grade/create.html.erb
<h1>Grade#create</h1>
<p>Find me in app/views/grade/create.html.erb</p>

app/views/grade/destroy.html.erb
<h1>Grade#destroy</h1>
<p>Find me in app/views/grade/destroy.html.erb</p>

app/views/grade/new.html.erb
<h1>Grade#new</h1>
<p>Find me in app/views/grade/new.html.erb</p>

app/views/grade/show.html.erb
<h1>Grade#show</h1>
<p>Find me in app/views/grade/show.html.erb</p>

app/views/parent/create.html.erb
<h1>Parent#create</h1>
<p>Find me in app/views/parent/create.html.erb</p>

app/views/parent/destroy.html.erb
<h1>Parent#destroy</h1>
<p>Find me in app/views/parent/destroy.html.erb</p>

app/views/parent/new.html.erb
<h1>Parent#new</h1>
<p>Find me in app/views/parent/new.html.erb</p>

app/views/parent/show.html.erb
<h1>Parent#show</h1>
<p>Find me in app/views/parent/show.html.erb</p>

app/views/student/create.html.erb
<h1>Student#create</h1>
<p>Find me in app/views/student/create.html.erb</p>

app/views/student/destroy.html.erb
<h1>Student#destroy</h1>
<p>Find me in app/views/student/destroy.html.erb</p>

app/views/student/new.html.erb
<h1>Student#new</h1>
<p>Find me in app/views/student/new.html.erb</p>

app/views/student/show.html.erb
<h1>Student#show</h1>
<p>Find me in app/views/student/show.html.erb</p>

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br>
    <%= f.text_field :password_digest %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Teachers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.name %></td>
        <td><%= teacher.email %></td>
        <td><%= teacher.password_digest %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @teacher.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @teacher.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @teacher.password_digest %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>